### ISSUE TITLE
Improve the D2Q444 scheme description

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#2]
Put a description similar to the 1D schemes description already proposed by Benjamin

**Comment by bgraille** [comment]
It's done. you can have a look and comment :)

**Comment by ThibautVanHoof** [comment]
Nice, thank you!

Some comments that are also available for the other scheme descriptions:
- looks like the '0' in the description of the lattice velocities do not appears ?   -( , $\lambda$) in the snapshot in attachment
- some formatting problems like extra space characters, comma and points, especially in the lists of 's'.
- add the formula relating the Henon and relaxation parameter (=1/s-0.5). 
- Henon parameter is called sigma in the code, maybe call it sigma too in the description
- Maybe relate sigma with the numerical diffusion in physical units (= sigma dx*la) which is more meaningful for most CFD users?
- Further precise the sentence:  "_The parameter $\lambda$ should be as small as possible while preserving the stability_". Maybe precise that small value allows to reduce the computational costs (number of steps)? Other reasons?

**Comment by ThibautVanHoof** [comment]
[SchemeDescriptionIssue_2.pdf](https://github.com/pylbm/pylbm_ui/files/6419828/SchemeDescriptionIssue_2.pdf)

**Comment by bgraille** [comment]
This issue is resolved for me in the branch `test_resume`. Tell me if it's good for you.

**Comment by ThibautVanHoof** [comment]
very nice scheme descriptions. Thanks a lot Benjamin!
I think I can close that issue.
