### ISSUE TITLE
Names of the responses too long / wrong

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#22]
The names of the responses are too long, especially when used 'as it' in the PCP which becomes totally unreadable for more than 4 axes. Moreover, they have to corresponds to the names used in the LBMHYPE final report for coherence. 

The simplest is to use the proposal class ResponsesWidget in the branch "fixPCP"

In practice:

- 'log of error avg on mass'  -> 'errAvg_Mass' (same for all fields)
- 'log of error std on mass'  -> 'errStd_Mass' (same for all fields)
- 'log of error on mass'  -> 'errEnd_Mass' (same for all fields), not used in the report but always interesting to have
- 'log of relative error on mass'  -> 'errRel_Mass' (same for all fields), not used in the report but always interesting  to have

- 'sigma for s_rho' ->  'Sig_rho'
- 'log of sigma for s_rho' ->  'LogSig_rho'
- 'diff for s_rho' -> 'Diff_rho'
- 'log of diff for s_rho' -> 'LogDiff_rho'
- 'diff with dx=1 for s_rho' -> 'DiffOdx_rho ' 
- 'log of diff with dx=1 for s_rho' -> 'LogDiffOdx_rho ' 
NOTE:  the expression 'log of diff with dx=1 for s_rho' is confusing since diff:=sigma dx**2/dt := sigma la dx using the first of the second or the second expression with dx = 1 will lead to different results! The real targeted response (associated with the onset of spurious oscillations) is diff/dx and is called 'DiffOdx' (for 'diff over dx') in the reports

**Comment by ThibautVanHoof** [comment]
status of version 4a25de3c051205d2602224bfed61cfe69612ca61 

The responses names in the widget is different from the responses name shown in PCP axes. That is not a real issue provided that both can be easily related. However, some mistakes append:

- the PCP axis name of the 'linear stability' response is <function build_responses_list.<locals>.<lambda> at 0x7f71540cf1f0>
- the PCP axis name of the 'log of diff with dx=1 for s_rho' response is "LogDiff_rho" which is wrong
- the 'log of diff with dx=1 for s_rho' is itself wrong, see the end of the previous post -> please use 'log of diff over dx for s_rho'  or 
'log of diff/dx for s_rho'

**Comment by gouarin** [comment]
fix in 54bee2b

**Comment by ThibautVanHoof** [comment]
second point of previous post not solved: the following pairs of values are still inverted:

- 'Diff_rho' and 'DiffOdx_rho' 
- 'LogDiff_rho' and 'LogDiffOdx_rho' 

the request of the following  responses lead to freezing of the PS during the evaluation: 

- 'log of error on XXX'  (XXX is a field, tested with XXX=mass)
- 'log of relative error on XXX'

**Comment by ThibautVanHoof** [comment]
Thanks for the corrections. 

Two errors 'log of error on mass' and 'log of relative error on mass' have the same axes name "err_mass" (XXX is the field name). 
Please use  'ErrEnd_Mass'  and   'ErrRel_Mass' respectively.

**Comment by gouarin** [comment]
Fix in https://github.com/pylbm/pylbm_ui/pull/31

**Comment by ThibautVanHoof** [comment]
The new names are 'AbsErr' and 'RelErr4. Please use 'ErrRel' and 'ErrAbs' for consistency with ErrStd and ErrAvg

**Comment by gouarin** [comment]
Then I prefer StdErr and AvgErr to keep the right order of the English expressions: Absolute Error, Relative Error, ...

**Comment by ThibautVanHoof** [comment]
OK

**Comment by gouarin** [comment]
Done in a2b0e05341a96b313b4ac4f4e6c62c4ae458c45c

**Comment by ThibautVanHoof** [comment]
Maybe change the extended responses names in the Responses widget accordingly for consistency? 

- log of avg error on mass
- log of std error on mass
- log of abs error on mass
- log of rel error on mass

**Comment by gouarin** [comment]
Fix in 0faabf0eaac53e73eaf77524eac63cbfe94f9c5c

**Comment by ThibautVanHoof** [comment]
thanks
