### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by rarygit** [pylbm/pylbm_ui#25]
OS: Ubuntu 20.04

Installed pylbm_ui as per instructions on GitHub page. 
Installation OK.

voila --debug voila.ipynb 
or
voila --debug /media/l1nux/SAN240/conda_envs/envs/pylbm_ui/voila.ipynb

Stops with AttributeError. 
Traceback output as below:

Thanks for any help to run "viola viola.ipynb"

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/pkgutil.py in get_importer(path_item)
    414     try:
--> 415         importer = sys.path_importer_cache[path_item]
    416     except KeyError:

KeyError: PosixPath('/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/schema')

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-99708c7e8018> in <module>
----> 1 from pylbm_ui.voila_main import main

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/pylbm_ui/__init__.py in <module>
      8 from . import simulation
      9 from . import responses
---> 10 from . import widgets

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/pylbm_ui/widgets/__init__.py in <module>
     11 from .stability import StabilityWidget
     12 from .simulation import SimulationWidget
---> 13 from .parametric_study import ParametricStudyWidget
     14 from .post_treatment import PostTreatmentWidget
     15 from .pylbmwidget import out

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/pylbm_ui/widgets/parametric_study.py in <module>
     22 
     23 from .debug import debug, debug_func
---> 24 from .design_space import DesignWidget, DesignItem
     25 from .dialog_path import DialogPath
     26 from .discretization import dx_validity

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/pylbm_ui/widgets/design_space.py in <module>
     14 from traitlets import Unicode, Float, List, Bool
     15 
---> 16 from schema.utils import SchemeVelocity, RelaxationParameterFinal
     17 
     18 from .debug import debug

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/schema/__init__.py in <module>
      8 from .utils import define_cases
      9 
---> 10 cases = define_cases(__file__, __name__)

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/schema/utils.py in define_cases(filename, modulename)
     42     gbl = globals()
     43     package_dir = Path(filename).resolve().parent
---> 44     for _, module_name, ispkg in iter_modules([package_dir]):
     45         if ispkg:
     46             module = f"{modulename}.{module_name}"

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/pkgutil.py in iter_modules(path, prefix)
    127 
    128     yielded = {}
--> 129     for i in importers:
    130         for name, ispkg in iter_importer_modules(i, prefix):
    131             if name not in yielded:

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/pkgutil.py in get_importer(path_item)
    417         for path_hook in sys.path_hooks:
    418             try:
--> 419                 importer = path_hook(path_item)
    420                 sys.path_importer_cache.setdefault(path_item, importer)
    421                 break

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in path_hook_for_FileFinder(path)

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in __init__(self, path, *loader_details)

/media/l1nux/SAN240/conda_envs/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in _path_isabs(path)

AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by gouarin** [comment]
We have an issue with Python version < 3.9.

Could you upgrade the python version to 3.9?

I will fix this issue soon.

**Comment by rarygit** [comment]
Many thanks @gouarin! 
'conda install python=3.9' upgraded from python v3.8 to v3.9.4 

voila voila.ipynb now works   :+1:
