### ISSUE TITLE
Linear stability tool is unstable

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#26]
The linear stability tool gives different results for the same states and scheme parameters during a test campaign.
Use Toro1 and D1Q333_0:

1. run stability analysis as it leas to all stable representative states, as expected
2. change lambda to 8 leads to unstablility for Star 2 state, as expected too
3. change back the value of lambda to 10 like in the first trial and now all the states are computed as linearly unstable!

first trial with default values:
![Screenshot from 2021-06-18 11-23-12](https://user-images.githubusercontent.com/57364219/122539641-1ab0dd80-d028-11eb-8181-e87bfc72ab45.png)

second trial with modified lambra=8:
![Screenshot from 2021-06-18 11-23-27](https://user-images.githubusercontent.com/57364219/122539755-3f0cba00-d028-11eb-923d-be4e503cbbd1.png)

third trial, back to default lambda value = 10:
![Screenshot from 2021-06-18 11-23-35](https://user-images.githubusercontent.com/57364219/122539761-4207aa80-d028-11eb-9b1b-c5164664deac.png)

**Comment by gouarin** [comment]
Fix in https://github.com/pylbm/pylbm_ui/pull/28

**Comment by ThibautVanHoof** [comment]
Thanks
