### ISSUE TITLE
Change simulation name lead to freeze

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#27]
The following sequence lead to freeze the simulation interface:

1. define and run a LBM simulation
3. click again on start and select NO in the popup window asking to replace the files
4. change the simulation name
5. click on start again -> freeze

**Comment by gouarin** [comment]
Fix in https://github.com/pylbm/pylbm_ui/pull/29

**Comment by ThibautVanHoof** [comment]
Thanks
