### ISSUE TITLE
Code generator useless in Parametric Studies

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#30]
The Code generator option of the Parametric study tab is useless since code generator is already define in the simulation tab.
Could you remove this option in the Parametric study tab and use the code generator define in the simulation tab only?

**Comment by gouarin** [comment]
Done in https://github.com/pylbm/pylbm_ui/pull/33

**Comment by ThibautVanHoof** [comment]
Thanks
