### ISSUE TITLE
Param study: add relaxation parameters 

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#34]
In the popup windows to add a relaxation parameter, the second widget is also called 'relaxation parameter'. Could you please rename it 'relaxation rates' which is more clear.

**Comment by gouarin** [comment]
Done in dc13106.

**Comment by ThibautVanHoof** [comment]
You change both the 'relaxation parameter' widgets to 'relaxation rates'. Could you change just the second? 

![Screenshot from 2021-06-21 15-10-09](https://user-images.githubusercontent.com/57364219/122784595-e4d35980-d2b2-11eb-80cb-ddaf4f88a510.png)

**Comment by gouarin** [comment]
I don't understand. I also changed this one.

Are you sure you're updated the UI correctly?

Le lun. 21 juin 2021 à 17:06, ThibautVanHoof ***@***.***> a
écrit :

**Comment by gouarin** [comment]
You mean: keep the first 'relaxation parameters' and change the second one by 'relaxation rates'?
I don't understand why you want to change only one.

**Comment by ThibautVanHoof** [comment]
Because  and the created design parameter will be a relaxation related parameter and the selected s_XXX in the second widget are relaxation rates

**Comment by gouarin** [comment]
Done in 203c268

**Comment by ThibautVanHoof** [comment]
Thanks
