### ISSUE TITLE
Change addvisc to 0.25 in D1Q333_0

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#35]
current value at line 156 of D1q333 file is addvisc = 0.5. Please change to 0.25 for consistency with the tests performed in LBMHYPE reports.

Note that it would be nice to add such internal scheme parameters in the interface to let the user:

1. know that it exist and may affect the results
2. play with the parameter value 

but for the moment, please just change the hard coded value

**Comment by gouarin** [comment]
Done in 49a30a8398629a2853ac20b452914629ef342758

**Comment by ThibautVanHoof** [comment]
Thanks
