### ISSUE TITLE
no data available in POST TREATMENT 

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#37]
Nothing to be plotted:  the .h5 in the /Outputs are no more listed in the POST TREATMENT tab (tested in version dc13106 and 335f04c)

**Comment by ThibautVanHoof** [comment]
KeyError                                  Traceback (most recent call last)
~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/pylbm_ui/widgets/post_treatment.py in update(self, change)
    449                 if 'simu_config.json' in f_names:
    450                     cfg = json.load(open(root + '/simu_config.json'))
--> 451                     if cfg['dim'] == self.select_dim.v_model:
    452                         dx = cfg['dx']
    453                         la = cfg['lb_scheme']['args']['la']

KeyError: 'dim'

**Comment by gouarin** [comment]
I think you have old outputs where the key 'dim' was not defined.
Could you remove these outputs or add the key 'dim' in the `simu_config.json` file ?

**Comment by ThibautVanHoof** [comment]
OK it works, thanks
