### ISSUE TITLE
'Period' for refreshing LBM SIMULATION viewer do not adapt to simulation 

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#39]
The Period for is set to 60 step and is not adapted to the current simulation. Could you makes it automatically adapted using Period  = Number of step / 10 . This mean 10 plot updates for the whole simulation by default

**Comment by gouarin** [comment]
This was the case before.

I think @bgraille changed that when the schemas defining the different cases were updated.

@bgraille  do you confirm?

**Comment by ThibautVanHoof** [comment]
Ok, you just have to push that functionality again ;-)

**Comment by bgraille** [comment]
In c793540 the period is adapted with the number of time steps: 
period = number_of_time_steps / nb_split_period (default nb_split_period is 10).
When the number of time steps is modified, the period changes.
And when the user modifies the period, then the number of time steps, the period is adapted to be conforme with the change of scales.

I think that this feature was not implemented before. Hope that this is what was needed...

**Comment by gouarin** [comment]
Thanks @bgraille !

**Comment by gouarin** [comment]
Do you really need to save the `nt` field?

**Comment by bgraille** [comment]
Yes !!! If the user changes by hand the period, the nb_split_period variable is no more useful. The other solution is to observe the change of period.v_model and modify nb_split_period.
Is it a better solution for you? I can do it!

**Comment by gouarin** [comment]
I'm not sure to understand.

It's always possible to update the period field using `nt` and `nb_split_period` using the formula you used in the initialization of the period field. For me, saving `nt` is used to retrieve `nb_split_period` but this value is a setting and can be used anywhere. 

Did I miss something?

**Comment by ThibautVanHoof** [comment]
I just assess the modification, the automatic modification of period is OK but the provided  period value wrong:

- Toro1 D1Q333_0: number of step = 250 but period is 24 (and not 250/10=25) 
- Toro2 D1Q333_0: number of step = 300 but period is 28 (and not 300/10=30) 

As a side effect, the final step of the simulation (certainly the most important for the user) is not shown.

**Comment by bgraille** [comment]
Right...
The problem is in the rounding. I'm not able to propose a good solution in the allotted time. So I impose the 10 images as you propose when the number of time steps is modified.
The fix is in 7db773e

**Comment by ThibautVanHoof** [comment]
Thanks Benjamin. Could you force the plot of the last step results in all cases (whatever the max number of iterations)?

**Comment by bgraille** [comment]
I force the plot and the save for the last time step in 4c623e9

**Comment by ThibautVanHoof** [comment]
Thanks, It's working now
