### ISSUE TITLE
Text description bug on local install

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#4]
The scheme description bug when the pylbm_ui is used in local. See the screenshot in attachment for more details. The test has been performed using a local installation following the procedure provided in the README. 
[pdfIssue.pdf](https://github.com/pylbm/pylbm_ui/files/6419893/pdfIssue.pdf)

**Comment by gouarin** [comment]
fix with 05ea1113853e0a94c8cde5ebba5d5258cc7af39f
