### ISSUE TITLE
Put the 'RUN PARAMETRIC STUDY' button in the analysis area

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#42]
The 'RUN PARAMETRIC STUDY'  is currently in the left panel below the PS definition widget. Put it in the analysis area (the right panel, at the top of the PCP if any) would allows for:

- highlight the button in a more visible default position (actually, It is not visible by default on my screen, I need to scroll)
- more consistent with the LBM SIMULATION tab where the similar 'START' button is already in the analysis area

**Comment by gouarin** [comment]
Done in 81690e78c7bdca000e801e2951fd6641625e2398

**Comment by ThibautVanHoof** [comment]
Thanks
