### ISSUE TITLE
issue with la value

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#44]
we try the implosion test case with the default parameters values and the following process:

1. run the simulation directly to obtain the reference results
2. change la from 15 (default) to 150
3. change la back from 150 to 15 (default)
4. run again the simulation and observe a different result -> very strange

**Comment by bgraille** [comment]
fix in 1d129c0

**Comment by ThibautVanHoof** [comment]
Thanks a lot @bgraille
