### ISSUE TITLE
Field output request: last step not saved

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#45]
tests performed using the implosion case:

- add an field output request with: Fields=All; When=Frequency;  When save the field?=1  -> the fields are saved at step  0 but not at the last step as expected
- add an field output request with: Fields=All; When=list of steps; When save the field?=Number of time steps (from the discretization widget)  -> nothing saved
- add an field output request with: Fields=All; When=list of steps; When save the field?=Number of time steps-1 (from the discretization widget)  -> results are saved

**Comment by bgraille** [comment]
Fix in 91c675e

**Comment by ThibautVanHoof** [comment]
Thanks @bgraille. It works perfect now
