### ISSUE TITLE
The reference results are not available for post treatment

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#6]
Accuracy assessment requires to compare the LBM fields with reference (when available like for the Toro cases). It requires to 
- Allows the user to save the reference field during the computations (at the same times than the LBM fields?)
- Make the reference fields available in the post treatment widget.

**Comment by gouarin** [comment]
fix in 6ec1e3e3eebf05c0235c646ecc203067fd41ca17
