### ISSUE TITLE
Download results do not work online

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#7]
All in the title. Note that a windows open if launched in local 

It is probably more flexible for the user analysis to allows downloading the whole directory for the current simulation or parametric study? -> displace the "download" widget from the POST-TREATMENT tab  to both the PARAMETRIC STUDY and the LBM SIMULATION tab

**Comment by gouarin** [comment]
fix in https://github.com/pylbm/pylbm_ui/pull/15
