### ISSUE TITLE
Improve the figure in POST_TREATMENT

### ISSUE THREAD

**Issue by ThibautVanHoof** [pylbm/pylbm_ui#8]
the figure could be improved with the following:
- add a legend (requested for readability in case of  multiple data in the same plots)
- Automatic configuration of the figure: adapt the axes name, the figure title and the legend text according to the selected data (see as an example the Cenaero prototype). Such small feature tends to improve the user productivity (less time to configure the plot -> more time to analyze)

**Comment by gouarin** [comment]
see https://github.com/pylbm/pylbm_ui/pull/16
